[tool.poetry]
name = "jaxmapse"
version = "0.1.0"
description = "JAX-based Matter Power Spectrum Emulator mirroring Mapse.jl"
authors = ["mbonici <bonici.marco@gmail.com>"]
readme = "README.md"
packages = [{include = "jaxmapse"}]

[tool.poetry.dependencies]
python = "^3.10"
jax = "^0.4.0"
jaxlib = "^0.4.0"
flax = "^0.10.0"
numpy = "^2.2.6"
jaxace = "^0.4.1"
jaxtyping = "^0.2.0"
typeguard = "^4.0.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
